name: Build and Release

on:
  push:
    tags:
      - "v*" # Only run on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/termagotchi-darwin-amd64 ./cmd/termagotchi
          GOOS=linux GOARCH=amd64 go build -o dist/termagotchi-linux-amd64 ./cmd/termagotchi
          GOOS=windows GOARCH=amd64 go build -o dist/termagotchi-windows-amd64.exe ./cmd/termagotchi

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
